version: '3.8'

services:
  coreapp:
    container_name: coreapp
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - SKIP_PREFLIGHT_CHECK=true
